version: "3"

services:
  app:
    image: guitest:latest
    build: .
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /home/sfeller/develop:/var/tmp/develop
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]
            count: all
networks:
  default:
    external: true
    name: 192.168.72.78
