version: "3"

services:
  app:
    image: mongo_dev
    build: .
    container_name: mongo_dev
    environment:
      - DISPLAY=${DISPLAY}
      - USER="${USER}"
      - HOME=/home/${USER}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /mnt/storage/develop:/home/sfeller/develop
    network_mode: host
  mongo:
    image: 'mongo:latest'
    ports:
      - '27017:27017'
    networks:
      - myapp

networks:
  myapp:
    driver: bridge
