version: "3"

services:
  app:
    image: guitest:latest
    build: .
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host

  mongo:
    image: 'mongo:latest'
    ports:
      - '27017:27017'
    networks:
      - myapp

networks:
  myapp:
    driver: bridge
